package by.bsuir.coursework.controller.command;

public enum CommandName {
    SIGN_IN, SIGN_UP, GO_TO_SIGN_UP_PAGE, GO_TO_SIGN_IN_PAGE, GO_TO_HOME_PAGE, EN_US, RU_RU, LOGOUT, GO_TO_VACANCY_PAGE,
    ADD_VACANCY, GO_TO_ADD_VACANCY_PAGE, GO_TO_USER_PROFILE_PAGE, DELETE_VACANCY, GO_TO_EDIT_VACANCY_PAGE, EDIT_VACANCY,
    ADD_CATEGORY, DELETE_CATEGORY, EDIT_CATEGORY, GO_TO_TYPES_PAGE, GO_TO_USERS_PAGE, DELETE_USER, GO_TO_EDIT_USER_PAGE,
    EDIT_USER, DELETE_COMMENT, SEARCH_ADS, FILTER_ADS, WRONG_REQUEST
}
