package by.bsuir.coursework.controller.command;

public enum CommandName {
    SIGN_IN, SIGN_UP, GO_TO_SIGN_UP_PAGE, GO_TO_SIGN_IN_PAGE, LOGOUT, GO_TO_HOME_PAGE, EN_US, RU_RU, GO_TO_VACANCY_PAGE,
    ADD_VACANCY, GO_TO_ADD_VACANCY_PAGE, DELETE_VACANCY, GO_TO_EDIT_VACANCY_PAGE, EDIT_VACANCY,
    ADD_PLATFORM, DELETE_PLATFORM, EDIT_PLATFORM, GO_TO_PLATFORMS_PAGE,
    GO_TO_USERS_PAGE, DELETE_USER, GO_TO_EDIT_USER_PAGE, EDIT_USER,
    GO_TO_INTERVIEWS_PAGE, GO_TO_ADD_INTERVIEW_PAGE, ADD_INTERVIEW, GO_TO_EDIT_INTERVIEW_PAGE, EDIT_INTERVIEW, DELETE_INTERVIEW,
    FILTER_VACANCIES_BY_SCHEDULE, FILTER_VACANCIES_BY_EMPLOYMENT, SEARCH_VACANCIES, SEARCH_INTERVIEWS, FILTER_INTERVIEWS,
    GO_TO_FEEDBACKS_PAGE, GO_TO_INTERVIEWER_FEEDBACKS_PAGE, ADD_FEEDBACK, EDIT_FEEDBACK, GO_TO_ADD_FEEDBACK_PAGE,
    GO_TO_EDIT_FEEDBACK_PAGE, GO_TO_PROFILE_PAGE, WRONG_REQUEST
}
